### ISSUE TITLE
Context around line

### ISSUE THREAD

**Issue by gerrywd** [jhbabon/scout#42]
This is a fantastic tool. It would be amazing to be able to specify a number of context lines to be displayed surrounding a match, such as with the -A -B and -C flags in grep.

**Comment by jhbabon** [comment]
Hello @gerrywd, thanks for your comment!

I've never thought about a feature like that. Let me see if I can find the time to add something like it.

**Comment by gerrywd** [comment]
🤞 Thank you for considering this. 😄

**Comment by jhbabon** [comment]
> 

Thanks for sharing this! I've never used `scout` that way, to be honest, I always use it to filter filepaths or list of items. This is very interesting.

Can you share an example of the command you use to filter through `man` pages? It might help me to refine this.

**Comment by gerrywd** [comment]
The same goes for git. You can `git blame <filename> | scout` and type the keyword that you wish to use to search for the appropriate change set. But I essentially want to use scout anywhere I would normally pipe to grep as it's just better.

**Comment by jhbabon** [comment]
> Maybe if hitting [tab] once you are on a line that could then show the context for the selected line? Perhaps that would be the best way?

That could be a good approach. I was thinking that too much context lines could clutter the results, but at the same time you want to quickly see what you are looking for. I'll need to think about this.

Thanks for all the feedback and suggestions, I appreciate it.

**Comment by gerrywd** [comment]
No worries at all. I agree regarding your point about the clutter, which is why maybe the key to activate might be better. An alternative that I've seen is to have a separate pane to the right, but I'm not sure as that might be a lot of effort. So whatever is the easiest for you would be my personal preference. Anyway, thanks for even considering the idea and making Scout. 👍

**Comment by jhbabon** [comment]
> No worries at all. I agree regarding your point about the clutter, which is why maybe the key to activate might be better. An alternative that I've seen is to have a separate pane to the right, but I'm not sure as that might be a lot of effort. So whatever is the easiest for you would be my personal preference. Anyway, thanks for even considering the idea and making Scout... (edit: and Github 😁 )

Yes, the right pane would be great, but printing to the `tty` is hard work and I would need to rework a lot of things to make it happen, mainly because I don't know what I'm doing most of the time 😅.

I hope I can find time soon to work on this.

**Comment by gerrywd** [comment]
> mainly because I don't know what I'm doing most of the time 😅.

I know the feeling 😁

**Comment by gerrywd** [comment]
Oh yikes! Thank you for your efforts! I'm sorry to hear it has been tricky. UI in the terminal is very difficult unless you are using some sort of framework and even then I'm not sure. I remember writing my own simple UI many many years ago using ncurses in C and it was brutal.

Just in case you haven't seen this one:
https://github.com/fdehau/tui-rs

Although I'm not sure how nicely this would play with your existing code. Perhaps that's some of the issues you are running into?

**Comment by jhbabon** [comment]
Yeah, I know `tui-rs`, it's pretty great. Sadly it doesn't work with my architecture which is based on `async/await`. I have an idea on how to improve the UI part, but it requires a whole rewrite, of that part at least, so it will take some time.

**Comment by jhbabon** [comment]
@gerrywd I'm very sorry about the radio silence. I was trying to put up together a new version with this feature, but I couldn't find the time. I'll keep working on it but it probably will take long. I'm going to close this issue but I'll ping you if I manage to release the new version. Thanks again for the feature request! 🙇🏻

**Comment by gerrywd** [comment]
@jhbabon no worries at all. It was only a suggestion and I can understand not having the time. Only keep working on it if it's something YOU really want. Live is too short to waste on random feature requests. Thank you for the honest response and thank you for the efforts you have put into this project. 👍 Stay awesome. 😃
