### ISSUE TITLE
[README] The instruction `$ find * -type f | scout | cat` doesn't print a file's contents

### ISSUE THREAD

**Issue by Pound-Hash** [jhbabon/scout#78]
Under [Usage](https://github.com/jhbabon/scout#usage), it says we can print a file's contents with `find * -type f | scout | cat`, but this prints a file's path instead.

**Comment by jhbabon** [comment]
Yeah, that's wrong, it should be:

```
find * -type f | scout | xargs -n1 cat
```

Thanks for finding this! I'll try to fix it soon.

**Comment by jhbabon** [comment]
And fixed. Thanks again!
